// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhRkbw_DA1SDKLhyvhJ8dRni7imY-QO1s',
    appId: '1:1072872920740:web:2f1f96833532c5377f3831',
    messagingSenderId: '1072872920740',
    projectId: 'moaeid',
    authDomain: 'moaeid.firebaseapp.com',
    storageBucket: 'moaeid.firebasestorage.app',
    measurementId: 'G-D7R34PQ9H3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDykYYa70cTbZZ8rjJHiwpV-PaWYTOIwoA',
    appId: '1:1072872920740:android:abe831ab0b29e0197f3831',
    messagingSenderId: '1072872920740',
    projectId: 'moaeid',
    storageBucket: 'moaeid.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-oWoBfHWC7CdY6TmN7sfqY5JOUz4vpxM',
    appId: '1:1072872920740:ios:742c054f241b5ddf7f3831',
    messagingSenderId: '1072872920740',
    projectId: 'moaeid',
    storageBucket: 'moaeid.firebasestorage.app',
    iosBundleId: 'com.example.mwaeedMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-oWoBfHWC7CdY6TmN7sfqY5JOUz4vpxM',
    appId: '1:1072872920740:ios:742c054f241b5ddf7f3831',
    messagingSenderId: '1072872920740',
    projectId: 'moaeid',
    storageBucket: 'moaeid.firebasestorage.app',
    iosBundleId: 'com.example.mwaeedMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhRkbw_DA1SDKLhyvhJ8dRni7imY-QO1s',
    appId: '1:1072872920740:web:f90daf096b8ce8ee7f3831',
    messagingSenderId: '1072872920740',
    projectId: 'moaeid',
    authDomain: 'moaeid.firebaseapp.com',
    storageBucket: 'moaeid.firebasestorage.app',
    measurementId: 'G-LQV8MHNTJR',
  );
}
